id: A78D80038
title: A Profound and Concise Guru Yoga
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:43:26.006469
  last_modified_at: 2022-02-28 22:43:26.006477
