id: A78D80038
title: Prayer for the Long Life of Namkhai Norbu Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:43:26.009175
  last_modified_at: 2022-02-28 22:43:26.009178
