id: A78D80038
title: Essence of All the Buddhas of Past, Present and Future
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:43:26.008175
  last_modified_at: 2022-02-28 22:43:26.008179
